# Generated by Django 2.2.5 on 2020-04-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200425_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='amenties',
            new_name='amenities',
        ),
    ]
